/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ich_common_zksnark_Libsodium_LibsodiumJNI */

#ifndef _Included_org_ich_common_zksnark_Libsodium_LibsodiumJNI
#define _Included_org_ich_common_zksnark_Libsodium_LibsodiumJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ich_common_zksnark_Libsodium_LibsodiumJNI
 * Method:    crypto_generichash_blake2b_state_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ich_common_zksnark_Libsodium_00024LibsodiumJNI_crypto_1generichash_1blake2b_1state_1init
  (JNIEnv *, jobject);

/*
 * Class:     org_ich_common_zksnark_Libsodium_LibsodiumJNI
 * Method:    crypto_generichash_blake2b_state_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ich_common_zksnark_Libsodium_00024LibsodiumJNI_crypto_1generichash_1blake2b_1state_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ich_common_zksnark_Libsodium_LibsodiumJNI
 * Method:    crypto_generichash_blake2b_init_salt_personal
 * Signature: (J[BII[B[B)I
 */
JNIEXPORT jint JNICALL Java_org_ich_common_zksnark_Libsodium_00024LibsodiumJNI_crypto_1generichash_1blake2b_1init_1salt_1personal
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     org_ich_common_zksnark_Libsodium_LibsodiumJNI
 * Method:    crypto_generichash_blake2b_update
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_org_ich_common_zksnark_Libsodium_00024LibsodiumJNI_crypto_1generichash_1blake2b_1update
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

/*
 * Class:     org_ich_common_zksnark_Libsodium_LibsodiumJNI
 * Method:    crypto_generichash_blake2b_final
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_org_ich_common_zksnark_Libsodium_00024LibsodiumJNI_crypto_1generichash_1blake2b_1final
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     org_ich_common_zksnark_Libsodium_LibsodiumJNI
 * Method:    crypto_generichash_blake2b_salt_personal
 * Signature: ([BI[BJ[BI[B[B)I
 */
JNIEXPORT jint JNICALL Java_org_ich_common_zksnark_Libsodium_00024LibsodiumJNI_crypto_1generichash_1blake2b_1salt_1personal
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jlong, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     org_ich_common_zksnark_Libsodium_LibsodiumJNI
 * Method:    crypto_aead_chacha20poly1305_ietf_decrypt
 * Signature: ([B[J[B[BJ[BJ[B[B)I
 */
JNIEXPORT jint JNICALL Java_org_ich_common_zksnark_Libsodium_00024LibsodiumJNI_crypto_1aead_1chacha20poly1305_1ietf_1decrypt
  (JNIEnv *, jobject, jbyteArray, jlongArray, jbyteArray, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_ich_common_zksnark_Libsodium_LibsodiumJNI
 * Method:    crypto_aead_chacha20poly1305_ietf_encrypt
 * Signature: ([B[J[BJ[BJ[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_org_ich_common_zksnark_Libsodium_00024LibsodiumJNI_crypto_1aead_1chacha20poly1305_1ietf_1encrypt
  (JNIEnv *, jobject, jbyteArray, jlongArray, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
